apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-vol
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: cinder-release
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
 
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pgbackup-daily-dump
spec:
  schedule: "00 01 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 2000
          containers:
          - name: pg_backup_alpinec
            image: internetuser2008/bimalalpine:latest
            command: ["sh", "-c", "./tmp/pg_backup.sh"]
            #  pgdumpDatabase.sh pg_backup.sh
            #        command: ["sh", "-c", "sleep 1h"]
            env:
            - name: PGHOST
              value: "mydeployment-postgresql-ha-pgpool"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "postgres"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "strongpassword"
            - name: PGBACKUPVOLUME
              value: "/pg_backup"
            - name: DAYS_TO_KEEP
              value: "31"
            - name: ENABLE_CUSTOM_BACKUPS
              value: "no"
            - name: ENABLE_PLAIN_BACKUPS
              value: "yes"
            - name: ENABLE_GLOBALS_BACKUPS
              value: "yes"
            - name: DAY_OF_WEEK_TO_KEEP
              value: "5"
            - name: DAYS_TO_KEEP
              value: "14"
            - name: WEEKS_TO_KEEP
              value: "2"
            - name: s3backup
              value: "yes"
            - name: S3_BUCKET
              value: "mybucket"
            - name: MINIO_URL
              value: "https://minio-rancher.mycrop.com"
            - name: AWS_ACCESS_KEY_ID
              value: "minio-xxxxxx"
            - name: AWS_SECRET_ACCESS_KEY
              value: "secret_access_key"
            - name: S3EXPIRE
              value: "7"
            - name: S3COPYMETHOD
              value: "cp"
            - name: AWS_DEFAULT_REGION
              value: "us-east-2"
            volumeMounts:
            - mountPath: "/pg_backup"
              name: pg-backup-vol
          volumes:
            - name: pg-backup-vol
              persistentVolumeClaim:
                claimName: postgres-backup-vol
      backoffLimit: 2
